### ISSUE TITLE
High energy impact (vscode on macOs)

### ISSUE THREAD

**Issue by giovdk21** [castwide/vscode-solargraph#117]
Might be related to #109, although I've been noticing this for a while and did not get notified about it. (I just spotted it looking at the activity monitor)

`OS`: macOS 10.14.4 (18E226)
`VSCode`: 1.34.0
`vscode-solargraph`: 0.19.6
`solargraph (gem)`: 0.32.3

When I open a ruby project (even a small one), with the solargraph extension enabled, the energy impact reported by activity monitor is very high (between 20 and 40% on average).

It then drops (to about 3%) if I close the project (while having other non-ruby projects open)

**Comment by castwide** [comment]
Thanks. I was finally able to reproduce this issue on a MacBook. I'll look further into it.

**Comment by castwide** [comment]
The root cause appears to be the client-server interface. Solargraph uses [Backport](https://github.com/castwide/backport) for event-driven IO. Backport was performing a lot of unnecessary polling, resulting in activity on threads that could have easily been sitting idle. My MacBook would show the Solargraph process at 10-12% CPU usage even when VS Code was sitting in the background.

This morning I released a new version of Backport that handles IO much more efficiently. Using the new version, Solargraph idles on my MacBook at about 1%. The change is in Solargraph's master branch. I expect to update the gem tomorrow.

**Comment by castwide** [comment]
This update also appears to have an impact on my Windows workstation. The polling problem wasn't apparent there, because the processor has enough power to show the Solargraph process idling at 0%. But under heavy activity, its CPU usage is decreased by about 25%.

**Comment by giovdk21** [comment]
That's great, many thanks!

Will test it in the upcoming days and I'll let you know

**Comment by castwide** [comment]
Gem v0.32.4 is published.

**Comment by giovdk21** [comment]
Just tested it quickly and seems to be working fine! Energy impact is now < 5% when idle.
Thanks again
