### ISSUE TITLE
Could solargraph go to definition in gems with Bundler?

### ISSUE THREAD

**Issue by shishi** [castwide/vscode-solargraph#125]
I saw "Solargraph and Bundler" and `solargraph.useBundler` is on, I can't go to the definition in gems like ActiveRecord.

```
class ApplicationRecord < ActiveRecord::Base # I can't go to ActiveRecord::Base
  self.abstract_class = true
end
```

I can go to the definition if the definition is in my application.

```
class Category < ApplicationRecord # I can go to ApplicatinRecord
  validates :name, presence: true, uniqueness: true
end
```

Do I miss other settings?

**Comment by castwide** [comment]
Rails uses `Bundler.require` to load gem dependencies instead of explicit `require` calls. As a result, Solargraph doesn't know they're required. This is an issue I plan to resolve in a future version, but for now there's a workaround. This gist should help: https://gist.github.com/castwide/28b349566a223dfb439a337aea29713e

There's an open issue regarding Rails support in Solargraph at https://github.com/castwide/solargraph/issues/87.

**Comment by shishi** [comment]
Thank you quick and detailed answer! 😄 
I really appreciate your hard working!
