### ISSUE TITLE
Keeps trying to yardoc my node projects

### ISSUE THREAD

**Issue by corbinu** [castwide/vscode-solargraph#13]
So I installed the extension as I am starting to work on a legacy Ruby project but now all day whenever I open an Node project in VSCode yardoc keeps generating a .yardoc and a doc directory despite the project I have open having no Ruby code in it. Seems like a bug.

Thanks!

**Comment by castwide** [comment]
Are you using any sort of Ruby-based software for builds or deployment, e.g., Capistrano? It's possible that opening files like Rakefile or Gemfile activate Solargraph and cause it to build a yardoc. I noticed this happens when I created a Gemfile in an Electron project that didn't contain any other Ruby.

It's also possible that you're getting false positives based on a common file extension that VS Code thinks might be Ruby, such as .spec or .builder.

At any rate, it does seem like a bug. The best solution might be to skip generating a yardoc unless the workspace contains .rb files.

**Comment by castwide** [comment]
I'm working on a possible solution in the Solargraph gem. I added a routine that checks the list of files that YARD would process. If the list is empty, the yardoc does not get generated.

**Comment by corbinu** [comment]
Thanks. No I am not. Maybe a .spec or .rb file is in the node_modules folder that's the only thing I can think of will dig a little deeper.

**Comment by castwide** [comment]
Okay, thanks. I have a feeling this WIP will resolve your issue, but it would definitely help to know what activated the extension.

**Comment by castwide** [comment]
Upcoming changes to the gem and extension should render this issue moot. The new Solargraph::ApiMap no longer requires a local yardoc file, so the extension will stop generating it. (See https://github.com/castwide/solargraph/issues/9 for more info)

**Comment by corbinu** [comment]
cool thanks!

**Comment by castwide** [comment]
Gem version 0.13.0 and extension version 0.9.0 are released. Yardocs are no longer generated automatically. YARD is still used for external gems, but it's not required in the workspace.
