### ISSUE TITLE
[solargraph socket] process make me computer crash,  because memory takes up 99%

### ISSUE THREAD

**Issue by doraemon0711** [castwide/vscode-solargraph#138]

**Comment by doraemon0711** [comment]
system is ubuntu18.04
solargraph gem is 0.35.2

**Comment by castwide** [comment]
Does this happen when you open a particular folder or workspace? There might be something in a gem dependency that makes Solargraph choke, or the problem might be the sheer size of the project, or it might be something I'm incapable of guessing .

**Comment by doraemon0711** [comment]
It's happened when i use vscode,but i'm not sure happened when open a particular folder or workspace.I can confirm is project is not sheer size.
Did you  know what's gem will make Solargraph choke?

**Comment by castwide** [comment]
I don't know of a particular gem that would cause a problem.

Can you provide a minimal example of a project that causes the problem?

**Comment by castwide** [comment]
I created a Gemfile with two minor changes:
1. Added `source 'https://rubygems.org'`
2. Deleted the `path` to `axlsx`

Then I ran `bundle install` and opened the folder in VS Code. I created a Ruby file with `require 'bundler/require'` so it would map all the gems. It took about 20 seconds to map, but it worked. The process used about 400MB of memory.

Assuming the problem is not a physical memory limitation, there might be something else in your code that's choking the language server.

**Comment by doraemon0711** [comment]
Thanks for your reply.
And just now,my coputer is  crashed.At that time,opened ruby  is two `models` and some used `Grape` created `api` file, and in thie file  maximum number of rows is 200, some model used `Solr` gem.
Is this information useful? Thanks

**Comment by castwide** [comment]
Are you running the Rails app and Solargraph at the same time? If so, can you determine how much memory Rails alone is using?

How much memory does your system have?

Do you have a swap file?

**Comment by doraemon0711** [comment]
No,i'm not running `rails server` or `rails console`, just use VSCode to coding.

This is puma used memory
![2019-08-09 14-18-50 的屏幕截图](https://user-images.githubusercontent.com/13547208/62758373-d873f800-bab0-11e9-8725-46d5b3d6013e.png)

My system memory is 8G, and swap file is 2G

This is `Solargraph socket` process used memory, but i'm not open any ruby file
![2019-08-09 14-24-47 的屏幕截图](https://user-images.githubusercontent.com/13547208/62758686-a9aa5180-bab1-11e9-996d-855ba31aeeee.png)

As time goes on, one `Solargraph socket` process's  MEM%  will be 15%

**Comment by castwide** [comment]
Thanks for the info. I suspect Solargraph's mapper is hitting code it can't process.

One more thing you can try. Go to your project's root directory and run `solargraph scan -v`. If the output throws an error or freezes, that might tell us where the problem is occurring. More information: https://solargraph.org/guides/scanning-workspaces

**Comment by doraemon0711** [comment]
I use `solargraph scan -v` for my project,it's output many info(39767 lines) in console, i'm `tee` this info to a txt file, but i can't find what's problem happend.

In weblink's info, possible bug will tell me error's location,but output info is like this
`Contact |  (/xxxxx/app/models/contact.rb 75)
 | :ref_type (/xxxxx/app/models/contact.rb 75)
 | :class_name (/xxxxx/app/models/contact.rb 76)`
i think is not error's location.
And another possible is entered an infinite loop, but in output end, print 
`xxxxxx (39765 pins) in 81.8124532569991 seconds.`
i think it's ok

**Comment by castwide** [comment]
Hmm. Yeah, if it got all the way to the end, it's probably not a mapper bug.

Are there any errors reported in VS Code's developer console (Help -> Toggle Developer Tools)?

**Comment by doraemon0711** [comment]
Thank you,when i find some errors, i'm talking to you, have nice day : )
