### ISSUE TITLE
Performance and config for bigger projects

### ISSUE THREAD

**Issue by theSoenke** [castwide/vscode-solargraph#17]
This is a really cool project and already works great in many cases. The only problem I have that it does not work for bigger projects. For example in a Rails application with > 100.000 lines of code the auto completion does not work at all.

As a solution I tried to only opened app/ with vscode. After this the auto completion was still a bit slow but started to work. I would still like to open the root folder so I created a .solargraph.yml config file to achieve a similar behavior:

```yml
---
include:
- "app/**/*.rb"
extensions: []
```

Unfortunately the auto completion still does not work. Am I missing something or is this an issue with the solargraph config?

**Comment by castwide** [comment]
Your .solargraph.yml file should be fine for Rails. Depending on the project, I might add `- "lib/**/*.rb"` to the include.

Other than that, I see two things that could be causing your issues: the size of the project and Rails itself.

## Large Projects

I've had the most success using Solargraph in small to medium projects, i.e., under 50k lines of code. Performance has steadily improved in the past few versions, but there's still more work to do.

I tested performance on large projects by opening the Rails project itself, which contains about 300k lines of code. Solargraph took just over a minute to map the workspace. Then I typed `A` in a Ruby file. It took about 40 seconds to return suggestions. The second request in the same space took about 25 seconds.

Next I opened one of Rails' subprojects, rails/actionpack, in a separate window. This one's about 60Kloc. Solargraph took about 10 seconds to map the workspace. I typed `A` in a Ruby file. It took about 5 seconds to return suggestions. Subsequent requests were instantaneous.

Long story short, I need to explore performance optimizations. Version 0.14.0 of the gem will include some slight improvements, but you'll probably still see lag in projects over 100K.

## Rails

There's a lot of magic happening in Rails. The mere fact that it dynamically requires dependencies hides a lot of its details from Solargraph. It also defines a lot of methods at runtime, where Solargraph can't see them.

### Partway There: Using Bundler

You can get partial information about Rails by running Solargraph with Bundler.

* Add this line to the Gemfile: `gem 'solargraph', group: :development`
* `$ bundle install`
* Open the project in VS Code
* In Code's workspace settings, set `solargraph.useBundler` to true

Example of the results:

    # app/models/user.rb
    class User < ActiveRecord::Base
    end
    User. # <- Suggestions include some methods from Rails

The above will give you some of the class methods defined by Rails, like `acts_like?` and `cache`. Unfortunately, it misses a lot of magic methods you might otherwise expect from an ActiveRecord, like `where`.

### A Little Closer: The Solargraph Rails Extension

Support for Solargraph extensions is currently in development. The first one is [solargraph-rails-ext](https://github.com/castwide/solargraph-rails-ext), which aims to solve some of the problems with magic methods. It works by opening a process that loads the Rails environment. The Solargraph server uses that process to query classes for more methods. Using the extension with the above example, suggestions for `User.` would include `where`.

One caveat: unlike the core Solargraph gem, _the Rails extension will actually execute some of your project's code_. It won't start a server, but it loads application code in much the same way as opening a Rails console.

Sorry I don't have better news for using Solargraph with 100K+ lines of code. I hope to continue improving performance as the project evolves.

**Comment by theSoenke** [comment]
Thanks for your detailed explanation. I still have a 2 questions.

1. How can I see how long it took to map the workspace? I waited a few minutes and still saw no completions for the full project.
2. I would expect that with the above .solargraph.yml config I would receive completions with a similar speed to only open app/ with VS Code but I don't get any suggestions. Any idea where the difference is coming from?

I have also now tested it with the Rails codebase and it took about 30s until it returned the first result. The codebase I'm working on has less lines than Rails. So could potentially something else slow solargraph down? Could the total number of and size of files have any effect (including those that do not end with .rb)? At least that is one major difference I see compared to the Rails project.

**Comment by castwide** [comment]
1. I had to estimate the mapping time by watching the console output in VS Code's developer tools. With the Rails codebase, the last output at the end of the process (on my machine, at least) is a YARD message:

    Error loading yardoc 'C:/Ruby23-x64/lib/ruby/gems/2.3.0/doc/capybara-2.13.0/.yardoc' ArgumentError undefined class/module SelectorObject

    Crude, I admit. The server should probably emit a message indicating the end of the process.

2. You're right, with that configuration the mapping process should be the same as opening /app directly. I assume the .solargraph.yml is in the workspace root?

How big is your project, in particular the file count? I wouldn't expect non-Ruby files to have an impact, but I suppose it's possible.

The number of gem dependencies and/or `require`'d paths can have a potential effect as well.

What kind of code is failing to provide suggestions? I would expect to get method suggestions for core classes, e.g. `String.` or `Array.`, even if the workspace was unmappable for some reason.

If you notice any errors in the VS Code console, especially anything with a stack trace, please let me know.

**Comment by theSoenke** [comment]
All completions were failing. Also no completions for classes like String were working. 

After I cleaned up tmp/ the number of files were reduce a lot to about 7000 files. Then I tried to delete directories basically by random and when I deleted config/ the autocompletion  suddenly worked after restarting solargraph. I had a closer look at the files in the config directory and deleting puma.rb fixed the completion. I've tried this multiple times and was always reproducible. I'm currently looking into it which part of the puma config could have caused this. At least now I have a working autocompletion. And it is even faster than I was expecting :)

As a simple fix instead of deleting the file I tried to exclude the file in .solargraph.yml but this had no effect. Neither excluding the specific file or the complete config directory worked for me.

```yml
---
include:
  - ./**/*.rb
exclude:
  - config/
extensions: []
```

**Comment by castwide** [comment]
Awesome! I'm glad you got it working.

As for the .solargraph.yml file, I think you hit a minor bug in file glob handling. If you list a folder name, it should assume you want to exclude all of the folder's contents, but it gets ignored instead. Folder names should work correctly in the next version. In the meantime, you should be able to make it work with a greedy wildcard:

    exclude:
      - config/**/*

**Comment by castwide** [comment]
I just looked at your last comment again and realized the file glob probably isn't the issue. I have a couple other ideas but need to dig deeper.

**Comment by castwide** [comment]
Also, if you want to c/p or attach the puma.rb that caused problems, it might help me troubleshoot.

**Comment by theSoenke** [comment]
It seems that `ActiveRecord::Base.establish_connection` breaks the completion. Here is an example puma.rb config. Commenting that line out fixes the autocompletion

```ruby
#!/usr/bin/env puma
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  ActiveRecord::Base.establish_connection
end
```

**Comment by castwide** [comment]
Thanks for tracking down the issue. I think gem v0.14.0 will resolve it. Among other things, it eliminates the need to load the Rails environment with solargraph-rails-ext.

If you're currently using solargraph-rails-ext, I recommend removing it from your Gemfile. All of its features are provided by the core gem now (currently in the master branch, soon to be released in 0.14.0). I may restart work on it in the future if there are other features that are better suited to an extension than the core.

**Comment by theSoenke** [comment]
Great! Thank you very much. I will try it as soon as the new version is released

**Comment by castwide** [comment]
The gem and extension have been updated. One of the potential issues, the Runtime plugin, has been disabled pending further troubleshooting.

**Comment by theSoenke** [comment]
Thanks for the update. Unfortunately the completions still do not work with when the puma.rb file is present. Also the exclusion in .solargraph.yml makes no difference. 

```yml
exclude:
  - config/**/*
```
Or
```yml
exclude:
  - config/puma.rb
```

But deleting puma.rb fixes the completions

**Comment by castwide** [comment]
Okay, thanks for letting me know. I'll take another look at it before the next update.

Just to confirm: are you using the `solargraph.useBundler` setting? It's false by default.

**Comment by theSoenke** [comment]
I did not use `solargraph.useBundler`. I've now also tried it with `solargraph.useBundler` but still the same result

**Comment by castwide** [comment]
I've reproduced the problem (or the symptoms, at least) on Windows and CentOS. It appears that the Puma configuration in the project impacts the instance of Puma that powers the Solargraph server.

The behavior is slightly different on each OS, but the result is the same. Both show errors in the VS Code console. On Windows, it says that worker mode is not supported. On CentOS, it throws a massive stack trace from an error involving Puma::DSL::ActiveRecord. Neither provides completions.

@theSoenke can you let me know if you're seeing any errors in the console now? The latest version of the gem should be more verbose about raised exceptions.

Assuming the problem is specific to Puma, the best solution might be to swap the server library that Solargraph uses from Puma back to WEBrick. The advantages of Puma for this use case appear to be small, and WEBrick has fewer moving parts.

I tested Solargraph using WEBrick with the same project and it worked as expected on both OSes.

I'm still not sure how the config/puma.rb in the project manages to effect the Solargraph server. The extension uses the workspace as the cwd for the server process, so Puma might automatically detect and load config/puma.rb. At any rate, if we can solve the problem by simply removing Puma from the equation, I think that'll cause less headaches down the road.

**Comment by theSoenke** [comment]
I'm running VSCode on Linux (Solus). I checked the console for error and I see 2 errors. They consistently appear when I try the completions. But I'm not sure whether this really helps: 

Error 1
```
The server is not running
```

Error 2
```
Cannot read property '$isError' of null: TypeError: Cannot read property '$isError' of null
    at MainThreadErrors.$onUnexpectedError (file:///usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:158701:20)
    at MainThreadService.AbstractThreadService.invoke (file:///usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:160784:27)
    at RPCProtocol._invokeHandler (file:///usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:139623:66)
    at RPCProtocol._receiveOneMessage (file:///usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:139612:47)
    at file:///usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:139558:92
    at file:///usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:139660:21
    at Emitter.fire (file:///usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:12889:38)
    at Socket.<anonymous> (file:///usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:21086:46)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
```

**Comment by castwide** [comment]
Thanks. That's consistent with my tests. The third error is new to me, but the first two come from solargraph-utils and VS Code itself after the server is already dead. The server errors vary by platform, but it looks like the root cause is always an exception while initializing Puma.

Switching the server back to WEBrick in the next update.

**Comment by castwide** [comment]
Gem version 0.14.3 is published.

In addition to fixing the Puma issue, performance in general should be a little improved, although large projects are still likely to yield significant lag. Testing on the Rails core again, it took about half a minute to map the workspace, and the initial suggestion requests took 2 to 5 seconds, but subsequent requests were often less than a second. Also in this version, the server will respond with partial suggestions while the workspace map is incomplete.

**Comment by theSoenke** [comment]
Awesome! This works already pretty good for me 🎉 

I'm still seeing a few warnings in the console:

```
"POST /resolve HTTP/1.1" 200 830
- -> /resolve
 (at Socket.child.stderr.on (/home/soenke/.vscode/extensions/castwide.solargraph-0.10.1/node_modules/solargraph-utils/out/Server.js:39:29))
```

```
(string):225:2: error: unexpected token $end
(string):225: _
(string):225:  
 (at Socket.child.stderr.on (/home/soenke/.vscode/extensions/castwide.solargraph-0.10.1/node_modules/solargraph-utils/out/Server.js:39:29))
```

```
unexpected token $end
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/diagnostic/engine.rb:71:in `process'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/base.rb:263:in `on_error'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/base.rb:162:in `parse'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/base.rb:179:in `parse_with_comments'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/base.rb:50:in `parse_with_comments'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/solargraph-0.14.3/lib/solargraph/api_map/source.rb:323:in `virtual'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/solargraph-0.14.3/lib/solargraph/api_map/source.rb:318:in `load'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/solargraph-0.14.3/lib/solargraph/api_map.rb:518:in `update'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/solargraph-0.14.3/lib/solargraph/server.rb:42:in `block in <class:Server>'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/null_logger.rb:9:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/show_exceptions.rb:22:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/home/soenke/.rbenv/versions/2.4.2/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
 (at Socket.child.stderr.on (/home/soenke/.vscode/extensions/castwide.solargraph-0.10.1/node_modules/solargraph-utils/out/Server.js:39:29))
```

**Comment by castwide** [comment]
Cool!

All those messages are routine debug output. The first one just indicates that the server received a request.

The second two look nasty, but they don't indicate a problem. In order to provide up-to-date results, the server will occasionally try to parse the file you're currently editing. If it runs into a problem with the syntax (for example, if you started an `if` statement but haven't given it an `end` yet), it logs the error and keeps going. I'll get rid of those messages (or at least make them less verbose) in an upcoming version.

**Comment by theSoenke** [comment]
Thanks for the explanation. I will then close this issue
