### ISSUE TITLE
Autocomplete doesn't work inside string interpolation

### ISSUE THREAD

**Issue by StefanoPernat** [castwide/vscode-solargraph#30]
First of all I'd thank you for your awesome work.
I discovered that inside string interpolation intellisense does not show any suggestion.

(see the attachment for an example)

Here's my configuration:
VSCode 1.21
Solargraph gem 0.17.3
![string_interpolation_autocomplete](https://user-images.githubusercontent.com/9131699/37173001-bae85254-2312-11e8-98b3-992e18af5836.png)

**Comment by castwide** [comment]
Thanks for the kind words and the report.

There's a fix for this issue in an upcoming version of the gem that includes support for Microsoft's language server protocol. I'll see if it's possible to backport the fix to the master branch, in which case it'll be fixed in gem version 0.17.4. If it can't be backported, it'll be in the first version that uses LSP, which I hope to release by the end of the month.

**Comment by castwide** [comment]
Autocomplete inside string interpolation works with the latest versions of the gem and extension.

**Comment by castwide** [comment]
This issue should be resolved. If anyone still has issues with autocompletion in strings, please open a new issue.
