### ISSUE TITLE
[NoMethodError] undefined method `parameters' for #<Solargraph::Pin::Attribute>

### ISSUE THREAD

**Issue by thomthom** [castwide/vscode-solargraph#70]
Been seeing this recently. Even with the latest updates today.

VSCode 1.25.0
VSCode-SolarGraph 0.17.4
SolarGraph Gem 0.23.3

```
[NoMethodError] undefined method `parameters' for #<Solargraph::Pin::Attribute:0x0000000cb48a78>
```

![2018-07-05_22h36_44](https://user-images.githubusercontent.com/192418/42346738-e6fdf350-80a3-11e8-838c-ca033c4931c9.png)

Not sure what triggers this. Any debug info I can provide that might help? Log?

**Comment by castwide** [comment]
Is there any additional information in the developer console?

I haven't been able to reproduce this bug, but I can make a general guess as to the root cause: some function of the map that analyzes method parameters is receiving an attribute, which is functionally equivalent to a method but never has parameters. It should be simple to fix.

**Comment by thomthom** [comment]
I don't recall observing anything. But I probably didn't check either.
I'll make sure to check if I see it next time. It doesn't happen consistently.

**Comment by thomthom** [comment]
Just saw it - I had closed the pane with Problems, Output, Debug Console and Terminal. Then shortly after the error notification appeared, opening the Output pane;

```
[Error - 11:03:29] Server initialization failed.
  Message: [NoMethodError] undefined method `parameters' for #<Solargraph::Pin::Attribute:0x000000126a17a8>
  Code: -32603 
```

Nothing in the Debug Console though.

**Comment by thomthom** [comment]
On the topic of `nil`, have you read Sandi Metz article "suspicions of nil"? https://www.sandimetz.com/blog/2014/12/19/suspicions-of-nil

Made me think about my use of returning `nil`.

**Comment by castwide** [comment]
@thomthom Good article, thanks. I read Sandi Metz's [_Practical Object-Oriented Design in Ruby_](https://www.amazon.com/Practical-Object-Oriented-Design-Agile-Primer/dp/0134456475/ref=sr_1_1?s=books&ie=UTF8&qid=1531071995&sr=1-1&keywords=sandi+metz) a few years ago and liked it a lot.

It definitely makes sense to avoid returning `nil` where possible. I'm working on a [testing tool](https://github.com/castwide/solargraph/issues/52) that logs return values that don't match a method's `@return` tag. When I use it on Solargraph, it finds ~22 methods that potentially return `nil` instead of the documented type. I'm not sure what to do about it yet, but I suspect at least some of those cases can be refactored into something better.

In this particular case, `Pin::Attribute` and `Pin::Method` are frequently treated as equivalent, but they have slightly different interfaces. For now I'm making sure they both have `parameters` methods; eventually it might make more sense for both to extend a common class that defines standard behavior for method-like pins.

**Comment by castwide** [comment]
Gem version 0.23.4 adds empty parameters to attributes. Please let me know if the problem persists.

**Comment by thomthom** [comment]
Installing it. I'll report back if I see it again.

Thank you very much for all your work and time invested in this. Great tools!

**Comment by thomthom** [comment]
Updated to 0.23.4 - and restarted VSCode. I got the message again. (And Solargraph doesn't appear to be running.)

![image](https://user-images.githubusercontent.com/192418/42462566-f1390816-83a3-11e8-8ed4-0dfebf46e39c.png)

I think I see it consistently with this one project of mine. Unfortunately it's a private repo...

Anything I can do to try to pull more information out of this?

**Comment by castwide** [comment]
Wow, that's a strange one. I would never expect the server to look for parameters on a namespace.

If you can come up with a test Ruby file that triggers the error, that would help a lot.

**Comment by castwide** [comment]
That's very possible. Solargraph both parses an AST and processes doc comments for (most of) the Ruby files in your workspace, and combines the information to build the map.

**Comment by thomthom** [comment]
I'll try to divide and conquer to find the culprit file.

**Comment by thomthom** [comment]
Ok, I've narrowed this down. In my project I have a Ruby C Extension project. Along with that I had Ruby headers and libs for both Windows and Mac. One of the Mac `ruby.framework` included the stdlib Ruby files. (Included by mistake.)

Removing them or excluding the ThirdParty directory I had eliminates the error I was seeing. This explains why I wasn't seeing it consistently - only on a select projects where I had similar setup.

I didn't look closer at why that error came up due to the `.framework`, as it sounds like too much of an edge case.
