### ISSUE TITLE
Go to definitions with RVM integration.

### ISSUE THREAD

**Issue by kopylovvlad** [castwide/vscode-solargraph#73]
I use this extension every day at my work, and I like it. Good and useful tool.

I think it will be better with  RVM support with gemset (as RubyMine).
I tried to add the path to one gem in the .solargraph.yml file:
```yml
include:
  - '**/*.rb'
  - '../../../.rvm/gems/ruby-2.4.4@gemset_test2/gems/roda-3.10.0/**/*.rb'
```
And it works perfectly!

But it has some troubles with performance:
I added the path to all gems:
```yml
include:
  - '**/*.rb'
  - '../../../.rvm/gems/ruby-2.4.4@gemset_test2/gems/**/*.rb'
```
It was starting the solargraph Language server too long. Solargraph-process used a lot of memory. And after click on "Go to Definition" I must wait for some minutes.

Do you have idea how to make it faster and better?

**Comment by castwide** [comment]
The best way to include gems in your workspace is to use YARD. Try this:

* Set the .solargraph `include` to `'**/*.rb'` only
* Run the following command in your workspace root to generate the YARD documentation:
  ```
  $ yard gems
  ```

The vscode-solargraph extension should automatically use your RVM environment when it starts the language server.

If everything works as expected, gems should get included in your code maps. For example, if your gemset includes `sidekiq`, the following should work:

```
require 'sidekiq'
Sidekiq:: # Completion items include classes, modules, and constants in the Sidekiq module
```

"Go to Definition" should also be able to find definitions from gems.

YARD documentation is usually good enough for gems, since you shouldn't need the maps of internal details included by Solargraph, and the gem's public API should be relatively static.

Improving performance for large-scale workspaces is an ongoing concern. I get good performance from the castwide/solargraph repo, which involves about 8K lines of parsed code and 12 active gems. Performance is significantly worse with the rails/rails repo, which involves about 133K lines of parsed code and 70+ active gems.

**Comment by kopylovvlad** [comment]
Thank you!
