### ISSUE TITLE
A new version of the Solargraph gem is available. Run `gem update solargraph` or update your Gemfile to install it.

### ISSUE THREAD

**Issue by monkeysuffrage** [castwide/vscode-solargraph#8]
This message is driving me crazy, any way to disable it?

**Comment by castwide** [comment]
Right now the only way to get rid of it is to update the gem. If you click "Update Now" in the message, that should take care of it. If you're using Bundler (the `solargraph.useBundler` setting), you'll need to `bundle update solargraph`.

Since there might be legitimate reasons to delay an update, I can add a configuration option to disable the check. I highly recommend using the latest version, though.

**Comment by castwide** [comment]
The newest version of the extension includes a `solargraph.checkGemVersion` setting which determines whether the extension should check for updates when it's activated. The default value is true.

There's also a `solargraph.checkGemVersion` command that can be used to check for updates manually.

**Comment by monkeysuffrage** [comment]
Awesome. Thank you bigly for your hard work on this great extension.
