### ISSUE TITLE
Solargraph process do not exit when opening a different folder or reloading window

### ISSUE THREAD

**Issue by whatalnk** [castwide/vscode-solargraph#96]
OS: Windows 10
Ruby: 2.6.0p0
Solargraph: 0.30.2
VSCode-extention: 0.19.1

I enjoy using this very nice extention, but solargraoh language server sometimes do not exit and multiple ruby process run simultaneously. 

Solargraph language server (ruby process in Windows Task Manager) starts when I open a ruby file. 
However, the ruby process do not close when I open a different folder, and new ruby process start when I open a ruby file. 
This is same as reloading window; new ruby process start whenever reloading window .

These ruby processes are still running after exiting VSCode. 

![Task Manager](https://user-images.githubusercontent.com/4127466/51085098-bbc04d80-1777-11e9-87ba-e6516607dd57.png)

**Comment by castwide** [comment]
One thing to keep in mind: if you run multiple VS Code windows at the same time, Solargraph will start one process for each window. This is because it's possible for different projects to have different runtime environments, e.g., different Ruby versions, bundles, gemsets, etc. The issue that is currently being fixed in v0.31.0 is Solargraph processes that keep running after you close VS Code.

An upcoming version of Solargraph might make it possible to attach multiple VS Code windows to a single process.
